In [1]:
%matplotlib inline
from typing import List, Dict, Tuple
from collections import Counter

import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_colwidth', None) # don't truncate cell contents

from tqdm.notebook import tqdm
tqdm.pandas()

import numpy as np
import matplotlib.pyplot as plt

import spacy

# from spacy.tokenizer import Tokenizer
from spacy.lang.en import English
nlp = spacy.load('/srv/scratch2/kew/spacy_models/en_core_web_sm-2.3.1/en_core_web_sm/en_core_web_sm-2.3.1', disable=["tagger", "parser", "ner"])

from sklearn.feature_extraction.text import TfidfVectorizer, TfidfTransformer

import multiprocessing_utils as mp

/mnt/storage/clwork/users/kew/INSTALLS/anaconda3/envs/respondelligent/lib/python3.8/site-packages/tqdm/std.py:670: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel


In [10]:
counts = ['cat zebra apple', 'cat zebra apple', 'banana lion apple elephant', 'elephant zebra elephant', 'elephant dog']

counts_lens = np.array([len(s.split()) for s in counts])
print(counts_lens)
transformer = TfidfVectorizer(smooth_idf=True, norm='l2')
tfidf = transformer.fit_transform(counts)
# print(tfidf)
# print(transformer.vocabulary_)
# print(dir(tfidf))
tfidf_array = tfidf.toarray()
# print(tfidf_array)
# print(tfidf_array.shape)


print(tfidf_array.sum(axis=1))
print(tfidf_array.sum(axis=1) / np.log(counts_lens))
# print(tfidf_array.sum(axis=1)

[3 3 4 3 2]
[1.72502774 1.72502774 1.9619827  1.34164079 1.38733127]
[1.57018792 1.57018792 1.41527135 1.22121407 2.00149594]
